// This property file was autogenerated by AutoSVA on 2024-04-16
// to check the behavior of the original RTL module, whose interface is described below: 


module imuldiv_IntMulIterative_prop
#(
		parameter ASSERT_INPUTS = 0)
(
		input                clk,
		input                reset,
		
		input  [31:0] mulreq_msg_a,
		input  [31:0] mulreq_msg_b,
		input         mulreq_val,
		input         mulreq_rdy, //output
		
		input  [63:0] mulresp_msg_result, //output
		input         mulresp_val, //output
		input         mulresp_rdy
	);

//==============================================================================
// Local Parameters
//==============================================================================

genvar j;
default clocking cb @(posedge clk);
endclocking
default disable iff (reset);

// Re-defined wires 

// Symbolics and Handshake signals

//==============================================================================
// Modeling
//==============================================================================


//X PROPAGATION ASSERTIONS
`ifdef XPROP
`endif

//====DESIGNER-ADDED-SVA====//
endmodule