// This property file was autogenerated by AutoSVA on 2024-04-16
// to check the behavior of the original RTL module, whose interface is described below: 


`include "imuldiv-DivReqMsg.v"

module imuldiv_IntDivIterative_prop
#(
		parameter ASSERT_INPUTS = 0)
(
		
		input         clk,
		input         reset,
		
		input         divreq_msg_fn,
		input  [31:0] divreq_msg_a,
		input  [31:0] divreq_msg_b,
		input         divreq_val,
		input         divreq_rdy, //output
		
		input  [63:0] divresp_msg_result, //output
		input         divresp_val, //output
		input         divresp_rdy
	);

//==============================================================================
// Local Parameters
//==============================================================================

genvar j;
default clocking cb @(posedge clk);
endclocking
default disable iff (reset);

// Re-defined wires 

// Symbolics and Handshake signals

//==============================================================================
// Modeling
//==============================================================================


//X PROPAGATION ASSERTIONS
`ifdef XPROP
`endif

//====DESIGNER-ADDED-SVA====//
endmodule